CREATE DATABASE formbase;

\c formbase;

-- creating schema api relations 
CREATE SCHEMA api; 

CREATE TABLE api.form (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR(255) NOT NULL, 
    description TEXT NOT NULL 
);

CREATE TABLE api.field (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id INTEGER NOT NULL REFERENCES api.form(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL, 
    field_type VARCHAR(9) NOT NULL CHECK (field_type IN ('text', 'multiline', 'dropdown', 'location')),
    options JSONB NOT NULL, 
    required BOOLEAN NOT NULL,
    is_num BOOLEAN NOT NULL, 
    order_index INTEGER NOT NULL
);

CREATE TABLE api.record (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    form_id INTEGER NOT NULL REFERENCES api.form(id) ON DELETE CASCADE, 
    values JSONB NOT NULL
);

-- creating roles and assign privileges
-- please enter your password
create role authenticator noinherit login password 'yourpassword';
-- postgREST can take on student role without needing a password
create role student nologin;
grant student to authenticator;
grant usage on schema api to student;
grant all on api.form to student;
grant all on api.field to student;
grant all on api.record to student;

-- populate with test data
INSERT INTO api.form (name, description) 
VALUES ('Research Form', 'A generic research form');
