CREATE DATABASE readysethire;

\c readysethire;

-- creating schema api relations 
CREATE SCHEMA api; 

CREATE TABLE api.interview (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    job_role VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) NOT NULL CHECK (status IN ('Published', 'Draft', 'Archived'))
);

CREATE TABLE api.question (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_id INTEGER NOT NULL REFERENCES api.interview(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    difficulty VARCHAR(20) NOT NULL CHECK (difficulty IN ('Easy', 'Intermediate', 'Advanced'))
);

CREATE TABLE api.applicant (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_id INTEGER NOT NULL REFERENCES api.interview(id) ON DELETE CASCADE,
    title VARCHAR(20) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    phone_number VARCHAR(50),
    email_address VARCHAR(255) NOT NULL,
    interview_status VARCHAR(50) NOT NULL CHECK (interview_status IN ('Not Started', 'Completed'))
);

CREATE TABLE api.applicant_answer (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_id INTEGER NOT NULL REFERENCES api.interview(id) ON DELETE CASCADE,
    question_id INTEGER NOT NULL REFERENCES api.question(id) ON DELETE CASCADE,
    applicant_id INTEGER NOT NULL REFERENCES api.applicant(id) ON DELETE CASCADE,
    answer TEXT
);

-- creating roles and assign privileges
-- please enter your password
create role authenticator noinherit login password 'yourpassword';
-- postgREST can take on student role without needing a password
create role student nologin;
grant student to authenticator;
grant usage on schema api to student;
grant all on api.interview to student;
grant all on api.question to student;
grant all on api.applicant to student;
grant all on api.applicant_answer to student;


-- populate with test data
INSERT INTO api.interview (title, job_role, description, status) 
VALUES ('Junior Developer', 'Developer', 'This is a description.', 'Draft');
